dsds.py:25,18:11:21:start:18:SzRhRg -- start
get_file:25,18:11:22:loadFiles:283:SzRhRg -- Start loadFiles, 527e4afc-4598-400f-8536-afa5324f0ba4 0B4Fujvv5MfqbVElBU01fZUxHcUk
requests:25,18:11:22:__call__:117:SzRhRg -- Making request: POST https://oauth2.googleapis.com/token
connecti:25,18:11:22:_new_conn:817:SzRhRg -- Starting new HTTPS connection (1): oauth2.googleapis.com
connecti:25,18:11:22:_make_request:393:SzRhRg -- https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
selector:25,18:11:22:__init__:59:SzRhRg -- Using selector: EpollSelector
test_uti:25,18:11:22:print_size:82:SzRhRg -- ---------------Memory usage: 94332 (kb)---------------0 mins since start
test_uti:25,18:11:22:print_size:88:SzRhRg -- /usr/lib/python3.8/tracemalloc.py:397: size=512 B (+512 B), count=3 (+3), average=171 B
test_uti:25,18:11:22:print_size:88:SzRhRg -- /usr/lib/python3.8/tracemalloc.py:534: size=472 B (+472 B), count=2 (+2), average=236 B
test_uti:25,18:11:22:print_size:88:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:82: size=448 B (+448 B), count=1 (+1), average=448 B
test_uti:25,18:11:22:print_size:88:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:86: size=424 B (+424 B), count=1 (+1), average=424 B
test_uti:25,18:11:22:print_size:88:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:79: size=0 B (-424 B), count=0 (-1)
test_uti:25,18:11:22:print_size:88:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:80: size=400 B (+400 B), count=1 (+1), average=400 B
test_uti:25,18:11:22:print_size:88:SzRhRg -- /usr/lib/python3.8/logging/__init__.py:330: size=48 B (+48 B), count=2 (+2), average=24 B
test_uti:25,18:11:22:print_size:88:SzRhRg -- /usr/lib/python3.8/tracemalloc.py:291: size=40 B (+40 B), count=1 (+1), average=40 B
test_uti:25,18:11:22:print_size:88:SzRhRg -- /usr/lib/python3.8/logging/__init__.py:329: size=24 B (+24 B), count=1 (+1), average=24 B
test_uti:25,18:11:22:print_size:88:SzRhRg -- /usr/lib/python3.8/logging/__init__.py:289: size=24 B (+24 B), count=1 (+1), average=24 B
test_uti:25,18:11:22:print_size:90:SzRhRg -- 

------------------------------


test_uti:25,18:11:22:print_size:93:SzRhRg -- /usr/lib/python3.8/tracemalloc.py:397: size=512 B, count=3, average=171 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /usr/lib/python3.8/tracemalloc.py:534: size=472 B, count=2, average=236 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:82: size=448 B, count=1, average=448 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:86: size=424 B, count=1, average=424 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:80: size=400 B, count=1, average=400 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /usr/lib/python3.8/logging/__init__.py:330: size=48 B, count=2, average=24 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /usr/lib/python3.8/tracemalloc.py:291: size=40 B, count=1, average=40 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /usr/lib/python3.8/logging/__init__.py:329: size=24 B, count=1, average=24 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /usr/lib/python3.8/logging/__init__.py:289: size=24 B, count=1, average=24 B
test_uti:25,18:11:22:print_size:93:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:83: size=24 B, count=1, average=24 B
test_uti:25,18:11:22:print_size:100:SzRhRg -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/0 at 2020-04-25 18:11:22.446553
dumped: 0
get_file:25,18:11:22:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:23:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:23:getRevision:166:SzRhRg -- getRevision looping
gdoc.py:25,18:11:23:async_init:24:SzRhRg -- async init called
get_file:25,18:11:23:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:23:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
gdoc.py:25,18:11:23:get_last_revision:53:SzRhRg -- last revision id 394
gdoc.py:25,18:11:23:async_init:33:SzRhRg -- after await 394
connecti:25,18:11:23:_new_conn:817:SzRhRg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:11:24:_make_request:393:SzRhRg -- https://docs.google.com:443 "GET /document/d/1TYIOfz_uzybWgEeexs8iE64jcjt-AmUegOP6KORNaWQ/revisions/load?id=1TYIOfz_uzybWgEeexs8iE64jcjt-AmUegOP6KORNaWQ&start=1&end=394 HTTP/1.1" 200 None
gdoc.py:25,18:11:24:download_details:68:SzRhRg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:11:24:getRevision:198:SzRhRg -- []
get_file:25,18:11:24:getRevision:201:SzRhRg -- google doc
get_file:25,18:11:24:getRevision:166:SzRhRg -- getRevision looping
gdoc.py:25,18:11:24:async_init:24:SzRhRg -- async init called
gdoc.py:25,18:11:24:get_last_revision:53:SzRhRg -- last revision id 1336
gdoc.py:25,18:11:24:async_init:33:SzRhRg -- after await 1336
connecti:25,18:11:24:_new_conn:817:SzRhRg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:11:24:_make_request:393:SzRhRg -- https://docs.google.com:443 "GET /document/d/19Fu317bfo0V7yOIkfLvKtAU-UJYLf8d2Soy-jTvq1uc/revisions/load?id=19Fu317bfo0V7yOIkfLvKtAU-UJYLf8d2Soy-jTvq1uc&start=1&end=1336 HTTP/1.1" 200 None
gdoc.py:25,18:11:24:download_details:68:SzRhRg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:11:24:getRevision:198:SzRhRg -- []
get_file:25,18:11:24:getRevision:201:SzRhRg -- google doc
get_file:25,18:11:24:getRevision:166:SzRhRg -- getRevision looping
get_file:25,18:11:24:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:25:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:25:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:25:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:26:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:26:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
get_file:25,18:11:27:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
test_uti:25,18:11:27:print_size:82:SzRhRg -- ---------------Memory usage: 94812 (kb)---------------0 mins since start
test_uti:25,18:11:27:print_size:88:SzRhRg -- <frozen importlib._bootstrap_external>:580: size=79.4 KiB (+79.4 KiB), count=939 (+939), average=87 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:158: size=16.4 KiB (+16.4 KiB), count=192 (+192), average=87 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- /home/henry/pydocs/processing/get_files.py:108: size=11.5 KiB (+11.5 KiB), count=274 (+274), average=43 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- /usr/lib/python3.8/ssl.py:906: size=10.6 KiB (+10.6 KiB), count=171 (+171), average=63 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- /usr/lib/python3.8/abc.py:102: size=9755 B (+9755 B), count=102 (+102), average=96 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- /home/henry/pydocs/processing/get_files.py:100: size=6070 B (+6070 B), count=82 (+82), average=74 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- /usr/lib/python3.8/asyncio/events.py:81: size=5144 B (+5144 B), count=17 (+17), average=303 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- /home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/aiohttp/client.py:850: size=3696 B (+3696 B), count=14 (+14), average=264 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- <frozen importlib._bootstrap>:219: size=3523 B (+3523 B), count=40 (+40), average=88 B
test_uti:25,18:11:27:print_size:88:SzRhRg -- /usr/lib/python3.8/concurrent/futures/thread.py:109: size=2999 B (+2999 B), count=12 (+12), average=250 B
test_uti:25,18:11:27:print_size:90:SzRhRg -- 

------------------------------


test_uti:25,18:11:27:print_size:93:SzRhRg -- <frozen importlib._bootstrap_external>:580: size=79.4 KiB, count=939, average=87 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- /home/henry/pydocs/processing/datutils/test_utils.py:158: size=16.4 KiB, count=192, average=87 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- /home/henry/pydocs/processing/get_files.py:108: size=11.5 KiB, count=274, average=43 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- /usr/lib/python3.8/ssl.py:906: size=10.6 KiB, count=171, average=63 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- /usr/lib/python3.8/abc.py:102: size=9755 B, count=102, average=96 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- /home/henry/pydocs/processing/get_files.py:100: size=6070 B, count=82, average=74 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- /usr/lib/python3.8/asyncio/events.py:81: size=5144 B, count=17, average=303 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- /home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/aiohttp/client.py:850: size=3696 B, count=14, average=264 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- <frozen importlib._bootstrap>:219: size=3523 B, count=40, average=88 B
test_uti:25,18:11:27:print_size:93:SzRhRg -- /usr/lib/python3.8/concurrent/futures/thread.py:109: size=2999 B, count=12, average=250 B
test_uti:25,18:11:27:print_size:100:SzRhRg -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
2/70 at 2020-04-25 18:11:27.530592
dumped: 0
get_file:25,18:11:27:getIdsRecursive:53:SzRhRg -- getIdsRecursive looping
test_uti:25,18:11:27:tryGetQueue:228:SzRhRg -- getIdswaiting 1 5
gdoc.py:25,18:11:28:async_init:24:SzRhRg -- async init called
gdoc.py:25,18:11:28:get_last_revision:53:SzRhRg -- last revision id 1946
gdoc.py:25,18:11:28:async_init:33:SzRhRg -- after await 1946
connecti:25,18:11:28:_new_conn:817:SzRhRg -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:11:29:_make_request:393:SzRhRg -- https://docs.google.com:443 "GET /document/d/1eXJKzIcZCM6pAdVLLrvEyIwQBDDrtm8dComeZ_W7uOI/revisions/load?id=1eXJKzIcZCM6pAdVLLrvEyIwQBDDrtm8dComeZ_W7uOI&start=1&end=1946 HTTP/1.1" 200 None
gdoc.py:25,18:11:29:download_details:68:SzRhRg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 66, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:11:29:getRevision:198:SzRhRg -- []
get_file:25,18:11:29:getRevision:201:SzRhRg -- google doc
get_file:25,18:11:29:getRevision:166:SzRhRg -- getRevision looping
gdoc.py:25,18:11:29:async_init:24:SzRhRg -- async init called
gdoc.py:25,18:11:29:get_last_revision:53:SzRhRg -- last revision id 12
gdoc.py:25,18:11:29:async_init:33:SzRhRg -- after await 12
connecti:25,18:11:29:_new_conn:817:SzRhRg -- Starting new HTTPS connection (1): docs.google.com
configlo:25,18:11:29:handle_exception:82:SzRhRg -- Custom Uncaught exception
Traceback (most recent call last):
  File "dsds.py", line 37, in <module>
    start()
  File "dsds.py", line 34, in start
    loadFiles(uid, workingPath, fileid, creds)
  File "/home/henry/pydocs/processing/get_files.py", line 308, in loadFiles
    loop.run_until_complete(asyncio.gather(startTask))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/henry/pydocs/processing/get_files.py", line 195, in getRevision
    dates = parent_conn.recv()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
configlo:25,18:11:29:sendmail:103:SzRhRg -- sending mail
gdoc.py:25,18:11:29:download_details:68:SzRhRg -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 65, in download_details
    response = requests.get(url = url, headers = self.headers)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/requests/adapters.py", line 430, in send
    resp = conn.urlopen(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/urllib3/connection.py", line 319, in connect
    self.sock = ssl_wrap_socket(
  File "/home/henry/.virtualenvs/pydocs/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt
configlo:25,18:11:31:handle_exception:86:SzRhRg -- exiting! from sshook
