configlo:25,16:21:44:sendmail:103:Uqymjw -- sending mail
configlo:25,16:21:45:handle_exception:82:Uqymjw -- Custom Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henry/pydocs/configlog.py", line 144, in sendmail
    with smtplib.SMTP_SSL("smtp.mailgun.org", 587, context=context) as server:
  File "/usr/lib/python3.8/smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 1042, in _get_socket
    new_socket = self.context.wrap_socket(new_socket,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)
configlo:25,16:21:45:sendmail:103:Uqymjw -- sending mail
configlo:25,16:22:25:sendmail:103:Uqymjw -- sending mail
configlo:25,16:22:25:handle_exception:82:Uqymjw -- Custom Uncaught exception
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henry/pydocs/configlog.py", line 144, in sendmail
    server.login(sender_email, password)
  File "/usr/lib/python3.8/smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.8/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 1042, in _get_socket
    new_socket = self.context.wrap_socket(new_socket,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)
configlo:25,16:22:25:sendmail:103:Uqymjw -- sending mail
