dsds.py:25,18:11:47:start:18:xWL0tA -- start
get_file:25,18:11:57:loadFiles:285:xWL0tA -- Start loadFiles, 527e4afc-4598-400f-8536-afa5324f0ba4 0B4Fujvv5MfqbVElBU01fZUxHcUk
requests:25,18:11:57:__call__:117:xWL0tA -- Making request: POST https://oauth2.googleapis.com/token
connecti:25,18:11:57:_new_conn:817:xWL0tA -- Starting new HTTPS connection (1): oauth2.googleapis.com
connecti:25,18:11:57:_make_request:393:xWL0tA -- https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
selector:25,18:11:57:__init__:59:xWL0tA -- Using selector: EpollSelector
test_uti:25,18:11:57:print_size:82:xWL0tA -- ---------------Memory usage: 94292 (kb)---------------0 mins since start
test_uti:25,18:11:57:print_size:88:xWL0tA -- /usr/lib/python3.8/tracemalloc.py:397: size=512 B (+512 B), count=3 (+3), average=171 B
test_uti:25,18:11:57:print_size:88:xWL0tA -- /usr/lib/python3.8/tracemalloc.py:534: size=472 B (+472 B), count=2 (+2), average=236 B
test_uti:25,18:11:57:print_size:88:xWL0tA -- /home/henry/pydocs/processing/datutils/test_utils.py:82: size=448 B (+448 B), count=1 (+1), average=448 B
test_uti:25,18:11:57:print_size:88:xWL0tA -- /home/henry/pydocs/processing/datutils/test_utils.py:86: size=424 B (+424 B), count=1 (+1), average=424 B
test_uti:25,18:11:57:print_size:88:xWL0tA -- /home/henry/pydocs/processing/datutils/test_utils.py:79: size=0 B (-424 B), count=0 (-1)
test_uti:25,18:11:57:print_size:88:xWL0tA -- /home/henry/pydocs/processing/datutils/test_utils.py:80: size=400 B (+400 B), count=1 (+1), average=400 B
test_uti:25,18:11:57:print_size:88:xWL0tA -- /usr/lib/python3.8/logging/__init__.py:330: size=48 B (+48 B), count=2 (+2), average=24 B
test_uti:25,18:11:57:print_size:88:xWL0tA -- /usr/lib/python3.8/tracemalloc.py:291: size=40 B (+40 B), count=1 (+1), average=40 B
test_uti:25,18:11:57:print_size:88:xWL0tA -- /usr/lib/python3.8/logging/__init__.py:329: size=24 B (+24 B), count=1 (+1), average=24 B
test_uti:25,18:11:57:print_size:88:xWL0tA -- /usr/lib/python3.8/logging/__init__.py:289: size=24 B (+24 B), count=1 (+1), average=24 B
test_uti:25,18:11:57:print_size:90:xWL0tA -- 

------------------------------


test_uti:25,18:11:57:print_size:93:xWL0tA -- /usr/lib/python3.8/tracemalloc.py:397: size=512 B, count=3, average=171 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /usr/lib/python3.8/tracemalloc.py:534: size=472 B, count=2, average=236 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /home/henry/pydocs/processing/datutils/test_utils.py:82: size=448 B, count=1, average=448 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /home/henry/pydocs/processing/datutils/test_utils.py:86: size=424 B, count=1, average=424 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /home/henry/pydocs/processing/datutils/test_utils.py:80: size=400 B, count=1, average=400 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /usr/lib/python3.8/logging/__init__.py:330: size=48 B, count=2, average=24 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /usr/lib/python3.8/tracemalloc.py:291: size=40 B, count=1, average=40 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /usr/lib/python3.8/logging/__init__.py:329: size=24 B, count=1, average=24 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /usr/lib/python3.8/logging/__init__.py:289: size=24 B, count=1, average=24 B
test_uti:25,18:11:57:print_size:93:xWL0tA -- /home/henry/pydocs/processing/datutils/test_utils.py:83: size=24 B, count=1, average=24 B
test_uti:25,18:11:57:print_size:100:xWL0tA -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/0 at 2020-04-25 18:11:57.694505
dumped: 0
get_file:25,18:11:57:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:11:58:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:11:58:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:11:59:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:12:00:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:12:00:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:12:01:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:12:01:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:12:01:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:12:02:getIdsRecursive:53:xWL0tA -- getIdsRecursive looping
get_file:25,18:12:02:getRevision:166:xWL0tA -- getRevision looping
gdoc.py:25,18:12:02:async_init:24:xWL0tA -- async init called
gdoc.py:25,18:12:02:get_last_revision:53:xWL0tA -- last revision id 394
gdoc.py:25,18:12:02:async_init:33:xWL0tA -- after await 394
configlo:25,18:12:02:handle_exception:82:xWL0tA -- Custom Uncaught exception
Traceback (most recent call last):
  File "dsds.py", line 37, in <module>
    start()
  File "dsds.py", line 34, in start
    loadFiles(uid, workingPath, fileid, creds)
  File "/home/henry/pydocs/processing/get_files.py", line 310, in loadFiles
    loop.run_until_complete(asyncio.gather(startTask))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/henry/pydocs/processing/get_files.py", line 248, in start
    await asyncio.gather(*revisionExplorer, *fileExplorers, printTask)
  File "/home/henry/pydocs/processing/get_files.py", line 190, in getRevision
    gd.download_details()
TypeError: download_details() missing 1 required positional argument: 'pipe'
configlo:25,18:12:02:sendmail:103:xWL0tA -- sending mail
configlo:25,18:12:03:handle_exception:86:xWL0tA -- exiting! from sshook
