dsds.py:25,18:17:06:start:18:yaG3Tw -- start
configlo:25,18:17:10:handle_exception:82:yaG3Tw -- Custom Uncaught exception
Traceback (most recent call last):
  File "dsds.py", line 37, in <module>
    start()
  File "dsds.py", line 34, in start
    loadFiles(uid, workingPath, fileid, creds)
  File "/home/henry/pydocs/processing/get_files.py", line 278, in loadFiles
KeyboardInterrupt
configlo:25,18:17:10:sendmail:103:yaG3Tw -- sending mail
configlo:25,18:17:11:handle_exception:86:yaG3Tw -- exiting! from sshook
