dsds.py:25,18:13:30:start:18:37EEOQ -- start
get_file:25,18:13:31:loadFiles:282:37EEOQ -- Start loadFiles, 527e4afc-4598-400f-8536-afa5324f0ba4 0B4Fujvv5MfqbVElBU01fZUxHcUk
requests:25,18:13:31:__call__:117:37EEOQ -- Making request: POST https://oauth2.googleapis.com/token
connecti:25,18:13:31:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): oauth2.googleapis.com
connecti:25,18:13:32:_make_request:393:37EEOQ -- https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
selector:25,18:13:32:__init__:59:37EEOQ -- Using selector: EpollSelector
test_uti:25,18:13:32:print_size:82:37EEOQ -- ---------------Memory usage: 94484 (kb)---------------0 mins since start
test_uti:25,18:13:32:print_size:100:37EEOQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/0 at 2020-04-25 18:13:32.101737
dumped: 0
get_file:25,18:13:32:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:32:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:33:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:33:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:34:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:34:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:34:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:35:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:35:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:36:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:36:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
get_file:25,18:13:36:getIdsRecursive:53:37EEOQ -- getIdsRecursive looping
test_uti:25,18:13:36:tryGetQueue:228:37EEOQ -- getIdswaiting 1 5
test_uti:25,18:13:37:print_size:82:37EEOQ -- ---------------Memory usage: 94740 (kb)---------------0 mins since start
test_uti:25,18:13:37:print_size:100:37EEOQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
0/74 at 2020-04-25 18:13:37.131441
dumped: 0
get_file:25,18:13:38:getRevision:166:37EEOQ -- getRevision looping
gdoc.py:25,18:13:38:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:38:get_last_revision:53:37EEOQ -- last revision id 394
gdoc.py:25,18:13:38:async_init:33:37EEOQ -- after await 394
connecti:25,18:13:38:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:38:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/1TYIOfz_uzybWgEeexs8iE64jcjt-AmUegOP6KORNaWQ/revisions/load?id=1TYIOfz_uzybWgEeexs8iE64jcjt-AmUegOP6KORNaWQ&start=1&end=394 HTTP/1.1" 200 None
gdoc.py:25,18:13:38:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:38:getRevision:197:37EEOQ -- []
get_file:25,18:13:38:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:38:getRevision:166:37EEOQ -- getRevision looping
gdoc.py:25,18:13:38:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:39:get_last_revision:53:37EEOQ -- last revision id 1336
gdoc.py:25,18:13:39:async_init:33:37EEOQ -- after await 1336
connecti:25,18:13:39:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:39:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/19Fu317bfo0V7yOIkfLvKtAU-UJYLf8d2Soy-jTvq1uc/revisions/load?id=19Fu317bfo0V7yOIkfLvKtAU-UJYLf8d2Soy-jTvq1uc&start=1&end=1336 HTTP/1.1" 200 None
gdoc.py:25,18:13:39:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:39:getRevision:197:37EEOQ -- []
get_file:25,18:13:39:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:39:getRevision:166:37EEOQ -- getRevision looping
gdoc.py:25,18:13:39:async_init:24:37EEOQ -- async init called
get_file:25,18:13:39:getRevision:166:37EEOQ -- getRevision looping
gdoc.py:25,18:13:39:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:40:get_last_revision:53:37EEOQ -- last revision id 1946
gdoc.py:25,18:13:40:async_init:33:37EEOQ -- after await 1946
connecti:25,18:13:40:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:40:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/1eXJKzIcZCM6pAdVLLrvEyIwQBDDrtm8dComeZ_W7uOI/revisions/load?id=1eXJKzIcZCM6pAdVLLrvEyIwQBDDrtm8dComeZ_W7uOI&start=1&end=1946 HTTP/1.1" 200 None
gdoc.py:25,18:13:40:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:40:getRevision:197:37EEOQ -- []
get_file:25,18:13:40:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:40:getRevision:166:37EEOQ -- getRevision looping
get_file:25,18:13:40:getRevision:183:37EEOQ -- not google doc
gdoc.py:25,18:13:40:get_last_revision:53:37EEOQ -- last revision id 12
gdoc.py:25,18:13:40:async_init:33:37EEOQ -- after await 12
connecti:25,18:13:40:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:41:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/1Ux4BA5BVJTcsGcTcGp8CtB85ahlWp0h83AGvrtAhnTg/revisions/load?id=1Ux4BA5BVJTcsGcTcGp8CtB85ahlWp0h83AGvrtAhnTg&start=1&end=12 HTTP/1.1" 200 None
gdoc.py:25,18:13:41:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:41:getRevision:197:37EEOQ -- []
get_file:25,18:13:41:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:41:getRevision:166:37EEOQ -- getRevision looping
get_file:25,18:13:41:getRevision:166:37EEOQ -- getRevision looping
test_uti:25,18:13:43:print_size:82:37EEOQ -- ---------------Memory usage: 95000 (kb)---------------0 mins since start
test_uti:25,18:13:43:print_size:100:37EEOQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
4/73 at 2020-04-25 18:13:43.033973
dumped: 0
get_file:25,18:13:43:getRevision:166:37EEOQ -- getRevision looping
gdoc.py:25,18:13:44:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:44:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:44:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:44:get_last_revision:53:37EEOQ -- last revision id 1394
gdoc.py:25,18:13:44:async_init:33:37EEOQ -- after await 1394
connecti:25,18:13:44:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:45:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/1K6SwyWCOhW6dt906DjOIhJ-ZklpsooCdTyYHGfEZD2s/revisions/load?id=1K6SwyWCOhW6dt906DjOIhJ-ZklpsooCdTyYHGfEZD2s&start=1&end=1394 HTTP/1.1" 200 None
gdoc.py:25,18:13:45:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:45:getRevision:197:37EEOQ -- []
get_file:25,18:13:45:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:45:getRevision:166:37EEOQ -- getRevision looping
test_uti:25,18:13:45:tryGetQueue:228:37EEOQ -- getIdswaiting 2 5
gdoc.py:25,18:13:45:get_last_revision:53:37EEOQ -- last revision id 1782
gdoc.py:25,18:13:45:async_init:33:37EEOQ -- after await 1782
connecti:25,18:13:45:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:45:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/1ak3AnxwEDfv_EkgRG7Q8U_eglT-eK2W3RtAJqlrtcQA/revisions/load?id=1ak3AnxwEDfv_EkgRG7Q8U_eglT-eK2W3RtAJqlrtcQA&start=1&end=1782 HTTP/1.1" 200 None
gdoc.py:25,18:13:45:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:45:getRevision:197:37EEOQ -- []
get_file:25,18:13:45:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:45:getRevision:166:37EEOQ -- getRevision looping
gdoc.py:25,18:13:45:get_last_revision:53:37EEOQ -- last revision id 6533
gdoc.py:25,18:13:45:async_init:33:37EEOQ -- after await 6533
connecti:25,18:13:45:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:46:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/1iTV26x-U2-nngY6gONVklMtrhdfI818IwLM682vpABA/revisions/load?id=1iTV26x-U2-nngY6gONVklMtrhdfI818IwLM682vpABA&start=1&end=6533 HTTP/1.1" 200 None
gdoc.py:25,18:13:46:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:46:getRevision:197:37EEOQ -- []
get_file:25,18:13:46:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:46:getRevision:166:37EEOQ -- getRevision looping
test_uti:25,18:13:48:print_size:82:37EEOQ -- ---------------Memory usage: 95000 (kb)---------------0 mins since start
test_uti:25,18:13:48:print_size:100:37EEOQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
8/74 at 2020-04-25 18:13:48.530502
dumped: 0
test_uti:25,18:13:48:compute_hist:145:37EEOQ -- []
test_uti:25,18:13:48:compute_hist:145:37EEOQ -- []
test_uti:25,18:13:48:compute_hist:145:37EEOQ -- []
test_uti:25,18:13:48:compute_hist:145:37EEOQ -- []
test_uti:25,18:13:48:compute_hist:145:37EEOQ -- [1463506197.898, 1463544450.442, 1464023145.545, 1464028629.148, 1464031723.639, 1464142009.92, 1464142184.618, 1464142004.131, 1464141985.407, 1464141230.049, 1464141228.955, 1464031900.981, 1464031720.411, 1464031404.229, 1464031223.686, 1464028760.711, 1464028580.304, 1464028399.835, 1464028218.938, 1464023323.261, 1464023142.822, 1464022962.236, 1464022781.687, 1464022525.729, 1464022343.716, 1463544450.49, 1463506213.536, 1463506198.92, 1463506198.246]
test_uti:25,18:13:48:compute_hist:145:37EEOQ -- []
test_uti:25,18:13:48:compute_hist:145:37EEOQ -- []
test_uti:25,18:13:48:compute_hist:145:37EEOQ -- []
test_uti:25,18:13:48:dump_files:136:37EEOQ -- histed files at /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/1.pathed, length 8
gdoc.py:25,18:13:50:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:50:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:50:async_init:24:37EEOQ -- async init called
gdoc.py:25,18:13:50:get_last_revision:53:37EEOQ -- last revision id 9
gdoc.py:25,18:13:50:async_init:33:37EEOQ -- after await 9
connecti:25,18:13:50:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:50:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/12x_9WkC_rJJ4iQW5IUNaY9BwAHRM1P6nRBi_oyRq7eI/revisions/load?id=12x_9WkC_rJJ4iQW5IUNaY9BwAHRM1P6nRBi_oyRq7eI&start=1&end=9 HTTP/1.1" 200 None
gdoc.py:25,18:13:50:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:50:getRevision:197:37EEOQ -- []
get_file:25,18:13:50:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:50:getRevision:166:37EEOQ -- getRevision looping
gdoc.py:25,18:13:50:get_last_revision:53:37EEOQ -- last revision id 1
gdoc.py:25,18:13:50:async_init:33:37EEOQ -- after await 1
connecti:25,18:13:50:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:51:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/1FzKITrCYnc_odhNCRNNaZ-PnT7m0f6qI-iDuQG382OY/revisions/load?id=1FzKITrCYnc_odhNCRNNaZ-PnT7m0f6qI-iDuQG382OY&start=1&end=1 HTTP/1.1" 200 None
gdoc.py:25,18:13:51:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:51:getRevision:197:37EEOQ -- []
get_file:25,18:13:51:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:51:getRevision:166:37EEOQ -- getRevision looping
gdoc.py:25,18:13:51:get_last_revision:53:37EEOQ -- last revision id 2999
gdoc.py:25,18:13:51:async_init:33:37EEOQ -- after await 2999
connecti:25,18:13:51:_new_conn:817:37EEOQ -- Starting new HTTPS connection (1): docs.google.com
connecti:25,18:13:52:_make_request:393:37EEOQ -- https://docs.google.com:443 "GET /document/d/1gKBPmWO42yparziEkHbvcBtubHyE_IQwtO1Q8IIrW1c/revisions/load?id=1gKBPmWO42yparziEkHbvcBtubHyE_IQwtO1Q8IIrW1c&start=1&end=2999 HTTP/1.1" 200 None
gdoc.py:25,18:13:52:download_details:69:37EEOQ -- Cannot get revisions.json
Traceback (most recent call last):
  File "/home/henry/pydocs/processing/gdoc.py", line 67, in download_details
    assert response.status == 200
AttributeError: 'Response' object has no attribute 'status'
get_file:25,18:13:52:getRevision:197:37EEOQ -- []
get_file:25,18:13:52:getRevision:200:37EEOQ -- google doc
get_file:25,18:13:52:getRevision:166:37EEOQ -- getRevision looping
test_uti:25,18:13:52:tryGetQueue:228:37EEOQ -- getIdswaiting 3 5
test_uti:25,18:13:53:print_size:82:37EEOQ -- ---------------Memory usage: 95000 (kb)---------------0 mins since start
test_uti:25,18:13:53:print_size:100:37EEOQ -- /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
11/74 at 2020-04-25 18:13:53.932667
dumped: 1
configlo:25,18:13:54:handle_exception:82:37EEOQ -- Custom Uncaught exception
Traceback (most recent call last):
  File "dsds.py", line 37, in <module>
    start()
  File "dsds.py", line 34, in start
    loadFiles(uid, workingPath, fileid, creds)
  File "/home/henry/pydocs/processing/get_files.py", line 307, in loadFiles
    loop.run_until_complete(asyncio.gather(startTask))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt
configlo:25,18:13:54:sendmail:103:37EEOQ -- sending mail
