sql.py:25,15:01:51:<module>:24:O2vglw -- Driver%3D%7BODBC+Driver+17+for+SQL+Server%7D%3BServer%3Dtcp%3Apydoc-db.database.windows.net%2C1433%3BDatabase%3Dpydocs%3BUid%3Dhenry2833%3BPwd%3D%7BInfoip32%7D%3BEncrypt%3Dyes%3BTrustServerCertificate%3Dno%3BConnection+Timeout%3D30%3B
sql.py:25,15:01:54:start:111:O2vglw -- STARTING SQL testing2020-04-25 15:01:54.424356 /home/henry/pydocs/data/527e4afc-4598-400f-8536-afa5324f0ba4/
sql.py:25,15:01:54:start:113:O2vglw -- setting sys except hook
sql.py:25,15:01:54:start:123:O2vglw -- Owner name: testing2020-04-04 25 AprpaQgfKRaVg
sql.py:25,15:01:55:start:127:O2vglw -- Added owner row, name: testing2020-04-04 25 AprpaQgfKRaVg id: 3
sql.py:25,15:01:55:start:139:O2vglw -- Finished loading pickles
sql.py:25,15:01:55:start:157:O2vglw -- File: 1NpTHMCkLa6lHL9Ok8a9hejyXihpujcQpVgSa7JNBP6s
sql.py:25,15:01:55:start:157:O2vglw -- File: 1JEcM-IFEodRvDg7EE9AntQ4wwOBTRXcDFqRK5SR2I08
sql.py:25,15:01:55:start:157:O2vglw -- File: 1LcO1aZmE6Jap4GF5ZpBGetjUSFeVBYg__DgWYlDwWY4
sql.py:25,15:01:55:start:177:O2vglw -- len of id map 3 len of files 3
sql.py:25,15:01:55:start:182:O2vglw -- starting bulk save
sql.py:25,15:01:55:adder:86:O2vglw -- flushing adder
sql.py:25,15:01:55:start:184:O2vglw -- bulked save done
sql.py:25,15:01:55:start:189:O2vglw -- File added, id: 7
sql.py:25,15:01:55:start:189:O2vglw -- File added, id: 8
sql.py:25,15:01:55:start:189:O2vglw -- File added, id: 9
sql.py:25,15:01:55:start:191:O2vglw -- sess flush done
sql.py:25,15:01:55:start:200:O2vglw -- adding dates for file: 7, dates to be added 2
sql.py:25,15:01:55:start:205:O2vglw -- [1580798526.504, 1580798743.99725, 1580798961.4905, 1580799178.9837499, 1580799396.477, 1580799613.9702501, 1580799831.4635, 1580800048.95675]
sql.py:25,15:01:55:start:206:O2vglw -- [134, 95, 37, 56, 66, 52, 37, 69]
sql.py:25,15:01:55:start:200:O2vglw -- adding dates for file: 8, dates to be added 2
sql.py:25,15:01:55:start:205:O2vglw -- [1552437584.445, 1552715059.6961427, 1552992534.9472857, 1553270010.1984286, 1553547485.4495714, 1553824960.700714, 1554102435.951857, 1554379911.203, 1554657386.4541428, 1554934861.7052855, 1555212336.9564285, 1555489812.2075715, 1555767287.4587142, 1556044762.709857]
sql.py:25,15:01:55:start:206:O2vglw -- [1153, 0, 0, 0, 0, 0, 0, 811, 0, 0, 0, 0, 0, 538]
sql.py:25,15:01:55:start:200:O2vglw -- adding dates for file: 9, dates to be added 2
sql.py:25,15:01:55:start:205:O2vglw -- [1586235205.136, 1586235476.1370769, 1586235747.1381538, 1586236018.1392307, 1586236289.1403077, 1586236560.1413846, 1586236831.1424615, 1586237102.1435385, 1586237373.1446154, 1586237644.1456923, 1586237915.1467693, 1586238186.1478462, 1586238457.1489232]
sql.py:25,15:01:55:start:206:O2vglw -- [69, 0, 20, 0, 6, 28, 107, 51, 80, 69, 47, 80, 90]
configlo:25,15:01:55:handle_exception:81:O2vglw -- Custom Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/henry/pydocs/processing/sql.py", line 322, in <module>
    start("testing" + datetime.now().__str__(), wpath)
  File "/home/henry/pydocs/processing/sql.py", line 212, in start
    logger.info(f"len dates: {len(lt_dates)}")
TypeError: object of type 'Queue' has no len()
configlo:25,15:01:57:handle_exception:85:O2vglw -- exiting! from sshook
